<a href="https://colab.research.google.com/github/mcapuccini/lazyprogrammer_courses/blob/master/Numpy_section_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Lists vs. Arrays

In [0]:
# Create a list in Python
L = [1,2,3]

# Create an array in Numpy
import numpy as np
A = np.array([1,2,3])

In [6]:
# Looping the list
for e in L:
    print(e)

# Looping the array
for e in A:
    print(e)

1
2
3
1
2
3


In [7]:
# + sing in Python concatenates 2 lists
L + L

[1, 2, 3, 1, 2, 3]

In [8]:
# + sing in Numpy sums 2 vectors (vecor/matrix addition)
A + A

array([2, 4, 6])

In [10]:
# * sign has similar story...
2*L

[1, 2, 3, 1, 2, 3]

In [11]:
2*A # element-wise multiplication

array([2, 4, 6])

In [12]:
# a bunch of element-wise operations in numpy
A**2

array([1, 4, 9])

In [13]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [14]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [15]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

### Dot product 1: For loop vs. cosine method vs. dot function


In [18]:
# Dot product: loop
a = np.array([1,2])
b = np.array([2,1])

dot = 0
for e, f in zip(a,b):
  dot += e*f
dot

4

In [19]:
# Dot product: elemeny-wise (1)
np.sum(a*b)

4

In [20]:
# Dot product 1: elemeny-wise (2)
(a*b).sum()

4

In [24]:
# Dot product: dot method
np.dot(a,b)

4

In [22]:
a.dot(b)

4

In [23]:
b.dot(a)

4

In [29]:
# Compute the angle
# Compute magnitude
amag = np.sqrt((a**2).sum())
amag

2.23606797749979

In [32]:
bmag = np.linalg.norm(b) # using linalg
bmag

2.23606797749979

In [35]:
# Compute cosine of the angle
cosangle = a.dot(b) / (amag * bmag)
cosangle

0.7999999999999998

In [36]:
np.arccos(cosangle) # printed in rad

0.6435011087932847

In [42]:
# Speed comparison: Dot product in Python vs Numpy
def python_dot_prod(a, b):
  dot = 0
  for e, f in zip(a,b):
    dot += e*f
  dot

a = np.random.randn(1000)
b = np.random.randn(1000)

from datetime import datetime
t0 = datetime.now()
python_dot_prod(a, b)
t_python = datetime.now() - t0

t0 = datetime.now()
a.dot(b)
t_numpy = datetime.now() - t0

t_python / t_numpy

6.119565217391305

### Vectors and matrices

In [0]:
# Matrix in numpy: array of arrays
M = np.array([[1,2],[3,4]])

In [0]:
# Matrix in python: array of arrays
L = [[1,2],[3,4]]

In [45]:
# Getting elements...
L[0][0]

1

In [46]:
M[0][0]

1

In [47]:
M[0,0]

1

In [0]:
# Matrix in numpy: matrix (NOT RECOMMENDED)
M2 = np.matrix([[1,2],[3,4]])

In [50]:
# Converting to array is a a good idea
np.array(M2)

array([[1, 2],
       [3, 4]])

In [51]:
# Convinient operations are available... e.g.
M.T

array([[1, 3],
       [2, 4]])

### Generating Matrices to Work With

In [54]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
np.random.random((10,10)) # uniformly distributed between 0 and 1

array([[0.71384758, 0.35793824, 0.77589089, 0.38548151, 0.60904429,
        0.98185979, 0.62920305, 0.25533686, 0.21158087, 0.24914371],
       [0.61917608, 0.65746829, 0.76559555, 0.34946272, 0.64981675,
        0.26047071, 0.25661511, 0.45766196, 0.6530947 , 0.33731078],
       [0.10641669, 0.30458632, 0.04319532, 0.58611297, 0.42813258,
        0.98501411, 0.03787516, 0.0921413 , 0.85883115, 0.2493294 ],
       [0.59742218, 0.07862404, 0.84388014, 0.60951822, 0.50080192,
        0.83708219, 0.21966345, 0.06740746, 0.97267645, 0.87822873],
       [0.15048516, 0.86714085, 0.5541447 , 0.32985551, 0.80915102,
        0.55239795, 0.07076099, 0.28164527, 0.09591762, 0.82449569],
       [0.19845329, 0.48032697, 0.57076754, 0.54944662, 0.06538019,
        0.14358067, 0.67462722, 0.5310664 , 0.98848943, 0.08233023],
       [0.07233107, 0.90116481, 0.85152105, 0.90019505, 0.95812171,
        0.56437869, 0.29717476, 0.48697377, 0.22884818, 0.6112242 ],
       [0.14329885, 0.72716979, 0.0892175

In [62]:
np.random.randn(10,10) # sample from gaussian distribution (mean 0, variance 1)

array([[ 0.43536318, -0.64388567, -0.27980073,  0.21558954, -1.34653841,
         1.73842365, -2.78097362,  0.4377664 ,  1.16635066, -1.28294087],
       [ 0.45398907, -1.79555615,  0.23429136,  0.21126616,  0.48161292,
         0.31741982, -0.95108801, -0.59385128, -0.88219701,  0.25457088],
       [ 0.05220027, -0.91669921, -0.10190397,  0.39982811, -0.45860444,
        -0.94774043, -0.99058204, -0.76814183,  1.42161133, -0.53978672],
       [ 0.4575143 ,  0.98715721,  0.48029382,  0.53553326,  1.89246249,
         0.4371431 ,  1.1229346 ,  0.14403591,  0.05963731, -1.42181332],
       [-0.57641287,  1.09955547, -0.54041473,  0.04065291, -1.26320882,
        -0.27842278,  0.6270146 ,  0.85215939, -0.63563496,  0.50499227],
       [-0.00875469, -2.08052396,  0.4040799 ,  0.61090742, -0.97437337,
         1.08645201, -0.05978435, -0.71875726, -0.56070479,  0.2524191 ],
       [ 0.75315457, -1.57599883, -0.90961941,  0.05556349,  0.65480539,
         0.80417304,  0.28496008, -0.94219278

In [66]:
np.random.randn(10,10).mean() # close to true value

-0.12270382431671804

In [67]:
np.random.randn(10,10).var() # close to true value

0.9226742056664815

### Matrix Products